version: "3.8"

services:
  #Это конфигурация Docker Compose для службы базы данных PostgreSQL используемой YAGPDB.
  yagpdb-postgres:
    container_name: yagpdb-postgres
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    env_file: postgres.env
    image: postgres:15-alpine
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "false"
    # ports:
    #   - "5432:5432"
    shm_size: 256mb
    volumes:
      - "/mnt/docker-volumes/db/yagpdb-postgres/data:/var/lib/postgresql/data"

networks:
  default:
    external: true
    name: $NETWORK
